;;; Generated by tools/generate-bindings.py from src/cl_wuffs.h. Do not edit.
(in-package #:cl-wuffs.bindings)

(defcstruct foreign-image
  (pixels :pointer)
  (length :size)
  (width :uint32)
  (height :uint32)
  (stride :uint32)
)

(defcfun ("cl_wuffs_detect_format" %detect-format) :int32
  (data :pointer)
  (length :size)
)

(defcfun ("cl_wuffs_decode_image" %decode-image) :int32
  (data :pointer)
  (length :size)
  (image :pointer)
  (error-message :pointer)
)

(defcfun ("cl_wuffs_adler32" %adler32) :uint32
  (data :pointer)
  (length :size)
)

(defcfun ("cl_wuffs_decompressor_create" %decompressor-create) :int32
  (format :int32)
  (literal-width :uint32)
  (decompressor :pointer)
  (error-message :pointer)
)

(defcfun ("cl_wuffs_decompressor_process" %decompressor-process) :int32
  (decompressor :pointer)
  (data :pointer)
  (length :size)
  (finish :boolean)
  (output :pointer)
  (output-length :pointer)
  (error-message :pointer)
)

(defcfun ("cl_wuffs_decompressor_free" %decompressor-free) :void
  (decompressor :pointer)
)

(defcfun ("cl_wuffs_free" %free) :void
  (pointer :pointer)
)
