;;; Generated by tools/generate-bindings.py from src/cl_wuffs.h. Do not edit.
(in-package #:cl-wuffs.bindings)

(defcstruct foreign-image
  (pixels :pointer)
  (length :size)
  (width :uint32)
  (height :uint32)
  (stride :uint32)
)

(defcstruct foreign-animation
  (frames :pointer)
  (durations-milliseconds :pointer)
  (frame-count :size)
  (loop-count :uint32)
)

(defcfun ("cl_wuffs_detect_format" %detect-format) :int32
  (data :pointer)
  (length :size)
)

(defcfun ("cl_wuffs_decode_image" %decode-image) :int32
  (data :pointer)
  (length :size)
  (image :pointer)
  (error-message :pointer)
)

(defcfun ("cl_wuffs_decode_animation" %decode-animation) :int32
  (data :pointer)
  (length :size)
  (animation :pointer)
  (error-message :pointer)
)

(defcfun ("cl_wuffs_animation_free" %animation-free) :void
  (animation :pointer)
)

(defcfun ("cl_wuffs_adler32" %adler32) :uint32
  (data :pointer)
  (length :size)
)

(defcfun ("cl_wuffs_crc32" %crc32) :uint32
  (data :pointer)
  (length :size)
)

(defcfun ("cl_wuffs_hasher_create" %hasher-create) :int32
  (algorithm :int32)
  (hasher :pointer)
  (error-message :pointer)
)

(defcfun ("cl_wuffs_hasher_update" %hasher-update) :int32
  (hasher :pointer)
  (data :pointer)
  (length :size)
  (digest :pointer)
  (error-message :pointer)
)

(defcfun ("cl_wuffs_hasher_free" %hasher-free) :void
  (hasher :pointer)
)

(defcfun ("cl_wuffs_decompressor_create" %decompressor-create) :int32
  (format :int32)
  (literal-width :uint32)
  (decompressor :pointer)
  (error-message :pointer)
)

(defcfun ("cl_wuffs_decompressor_process" %decompressor-process) :int32
  (decompressor :pointer)
  (data :pointer)
  (length :size)
  (finish :boolean)
  (output :pointer)
  (output-length :pointer)
  (error-message :pointer)
)

(defcfun ("cl_wuffs_decompressor_free" %decompressor-free) :void
  (decompressor :pointer)
)

(defcfun ("cl_wuffs_free" %free) :void
  (pointer :pointer)
)
