(in-package #:cl-wuffs.bindings)
(define-foreign-library cl-wuffs (:darwin (:or "libcl_wuffs.dylib" "cl_wuffs.dylib")) (t (:default "cl_wuffs")))
(defvar *library-loaded* nil)
(defun load-library () (unless *library-loaded* (let ((pathname (uiop:getenv "CL_WUFFS_LIBRARY"))) (if pathname (load-foreign-library pathname) (use-foreign-library cl-wuffs))) (setf *library-loaded* t)))
(defun detect-format (octets) (load-library) (with-pointer-to-vector-data (data octets) (%detect-format data (length octets))))
(defun decode-image (octets) (load-library) (let ((image (foreign-alloc '(:struct foreign-image)))) (with-foreign-object (message :pointer) (with-pointer-to-vector-data (data octets) (let ((status (%decode-image data (length octets) image message))) (values image status (unless (zerop status) (foreign-string-to-lisp (mem-ref message :pointer)))))))))
(defun adler32 (octets) (load-library) (with-pointer-to-vector-data (data octets) (%adler32 data (length octets))))
(defun free-image (image) (load-library) (%free (foreign-slot-value image '(:struct foreign-image) 'pixels)) (foreign-free image))
(defun foreign-image-pixels (image) (foreign-slot-value image '(:struct foreign-image) 'pixels))
(defun foreign-image-length (image) (foreign-slot-value image '(:struct foreign-image) 'length))
(defun foreign-image-width (image) (foreign-slot-value image '(:struct foreign-image) 'width))
(defun foreign-image-height (image) (foreign-slot-value image '(:struct foreign-image) 'height))
(defun foreign-image-stride (image) (foreign-slot-value image '(:struct foreign-image) 'stride))
