(in-package #:cl-wuffs.bindings)
(define-foreign-library cl-wuffs (:darwin (:or "libcl_wuffs.dylib" "cl_wuffs.dylib")) (t (:default "cl_wuffs")))
(defvar *library-loaded* nil)
(defun load-library () (unless *library-loaded* (let ((pathname (uiop:getenv "CL_WUFFS_LIBRARY"))) (if pathname (load-foreign-library pathname) (use-foreign-library cl-wuffs))) (setf *library-loaded* t)))
(defun detect-format (octets) (load-library) (with-pointer-to-vector-data (data octets) (%detect-format data (length octets))))
(defun decode-image (octets) (load-library) (let ((image (foreign-alloc '(:struct foreign-image)))) (with-foreign-object (message :pointer) (with-pointer-to-vector-data (data octets) (let ((status (%decode-image data (length octets) image message))) (values image status (unless (zerop status) (foreign-string-to-lisp (mem-ref message :pointer)))))))))
(defun decode-animation (octets)
  (load-library)
  (let ((animation (foreign-alloc '(:struct foreign-animation))))
    (with-foreign-object (message :pointer)
      (with-pointer-to-vector-data (data octets)
        (let ((status (%decode-animation data (length octets) animation message)))
          (values animation status
                  (unless (zerop status) (foreign-string-to-lisp (mem-ref message :pointer)))))))))
(defun free-animation (animation) (load-library) (%animation-free animation) (foreign-free animation))
(defun adler32 (octets) (load-library) (with-pointer-to-vector-data (data octets) (%adler32 data (length octets))))
(defun crc32 (octets) (load-library) (with-pointer-to-vector-data (data octets) (%crc32 data (length octets))))
(defun hasher-create (algorithm)
  (load-library)
  (with-foreign-object (handle :pointer)
    (with-foreign-object (message :pointer)
      (let ((status (%hasher-create algorithm handle message)))
        (values (mem-ref handle :pointer) status
                (unless (zerop status) (foreign-string-to-lisp (mem-ref message :pointer))))))))
(defun hasher-update (handle octets)
  (load-library)
  (with-foreign-object (digest :uint32)
    (with-foreign-object (message :pointer)
      (with-pointer-to-vector-data (data octets)
        (let ((status (%hasher-update handle data (length octets) digest message)))
          (values (mem-ref digest :uint32) status
                  (unless (zerop status) (foreign-string-to-lisp (mem-ref message :pointer)))))))))
(defun hasher-free (handle) (load-library) (%hasher-free handle))
(defun free-image (image) (load-library) (%free (foreign-slot-value image '(:struct foreign-image) 'pixels)) (foreign-free image))
(defun foreign-image-pixels (image) (foreign-slot-value image '(:struct foreign-image) 'pixels))
(defun foreign-image-length (image) (foreign-slot-value image '(:struct foreign-image) 'length))
(defun foreign-image-width (image) (foreign-slot-value image '(:struct foreign-image) 'width))
(defun foreign-image-height (image) (foreign-slot-value image '(:struct foreign-image) 'height))
(defun foreign-image-stride (image) (foreign-slot-value image '(:struct foreign-image) 'stride))
(defun decompressor-create (format literal-width)
  (load-library)
  (with-foreign-object (handle :pointer)
    (with-foreign-object (message :pointer)
      (let ((status (%decompressor-create format literal-width handle message)))
        (values (mem-ref handle :pointer) status
                (unless (zerop status) (foreign-string-to-lisp (mem-ref message :pointer))))))))
(defun decompressor-process (handle octets finish)
  (load-library)
  (with-foreign-object (output :pointer)
    (with-foreign-object (output-length :size)
      (with-foreign-object (message :pointer)
        (with-pointer-to-vector-data (data octets)
          (let ((status (%decompressor-process handle data (length octets) finish output output-length message)))
            (if (zerop status)
                (let* ((length (mem-ref output-length :size))
                       (bytes (make-array length :element-type '(unsigned-byte 8))))
                  (unwind-protect
                       (progn
                         (when (plusp length)
                           (with-pointer-to-vector-data (destination bytes)
                             (foreign-funcall "memcpy" :pointer destination :pointer (mem-ref output :pointer) :size length :pointer)))
                         (values bytes status nil))
                    (%free (mem-ref output :pointer))))
                (values nil status (foreign-string-to-lisp (mem-ref message :pointer))))))))))
(defun decompressor-free (handle) (load-library) (%decompressor-free handle))
