#!/usr/bin/env python3
"""Generate CFFI declarations from the public cl_wuffs C ABI."""
import json, pathlib, subprocess, sys
ROOT = pathlib.Path(__file__).resolve().parents[1]
HEADER, OUTPUT = ROOT / "include/cl_wuffs.h", ROOT / "lisp/bindings/generated.lisp"
TYPES = {"void": ":void", "int32_t": ":int32", "uint32_t": ":uint32", "size_t": ":size"}
def walk(node):
    yield node
    for child in node.get("inner", []): yield from walk(child)
def typ(value): return ":pointer" if "*" in value or "[" in value else TYPES.get(value, ":pointer")
def name(value): return value.replace("_", "-")
clang = sys.argv[1] if len(sys.argv) == 2 else "clang"
ast = json.loads(subprocess.run([clang, "-x", "c", "-Xclang", "-ast-dump=json", "-fsyntax-only", str(HEADER)], check=True, capture_output=True, text=True).stdout)
nodes = list(walk(ast))
record = next(n for n in nodes if n.get("kind") == "RecordDecl" and n.get("name") == "cl_wuffs_image" and n.get("completeDefinition"))
functions = [n for n in nodes if n.get("kind") == "FunctionDecl" and n.get("name", "").startswith("cl_wuffs_")]
if not functions: raise SystemExit("no cl_wuffs functions found")
out = [";;; Generated by tools/generate-bindings.py from include/cl_wuffs.h. Do not edit.", "(in-package #:cl-wuffs.bindings)", "", "(defcstruct foreign-image"]
out += [f"  ({name(n['name'])} {typ(n['type']['qualType'])})" for n in record.get("inner", []) if n.get("kind") == "FieldDecl"]
out += [")", ""]
for fun in functions:
    ret = typ(fun["type"]["qualType"].split(" (")[0])
    out.append(f"(defcfun (\"{fun['name']}\" %{name(fun['name'][9:])}) {ret}")
    out += [f"  ({name(n['name'])} {typ(n['type']['qualType'])})" for n in fun.get("inner", []) if n.get("kind") == "ParmVarDecl"]
    out += [")", ""]
OUTPUT.write_text("\n".join(out))
